spring.application.name=260223_PosWmcProject_VidbeCheck

#####################################################
# LogLevel
#####################################################
logging.level.sc = info

#####################################################
# Datasource
#####################################################
#spring.datasource.url=jdbc:postgresql://localhost:5432/_2526_4dpos_vibecheck
# DOCKER
spring.datasource.url=jdbc:postgresql://postgres:5432/_2526_4dpos_vibecheck
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
